---
kind: "operation"
client: "rug-cli 0.16.6"
editor:
  name: "EnableTravisForRugArchiveTS"
  group: "atomist-rugs"
  artifact: "travis-editors"
  version: "0.3.0"
  origin:
    repo: "atomist-rugs/travis-editors.git"
    branch: "master"
    sha: "b4541d3*"
  parameters:
    - "repo_slug": "atomist-rugs/travis-editors"
    - "org": ".org"
    - "github_token": "4**************************************b"
    - "maven_base_url": "https://atomist.jfrog.io/atomist"
    - "maven_user": "t************h"
    - "maven_token": "A***********************************************************************i"

---
kind: "operation"
client: "rug-cli 0.20.0-SNAPSHOT"
editor:
  name: "UpdateTravisMaven"
  group: "atomist-rugs"
  artifact: "travis-editors"
  version: "0.7.0"
  origin:
    repo: "atomist-rugs/travis-editors.git"
    branch: "master"
    sha: "b910aef*"

---
kind: "operation"
client: "rug-cli 0.20.0-SNAPSHOT"
editor:
  name: "UpdateTravisMaven"
  group: "atomist-rugs"
  artifact: "travis-editors"
  version: "0.7.0"
  origin:
    repo: "atomist-rugs/travis-editors.git"
    branch: "master"
    sha: "b910aef*"

---
kind: "operation"
client: "rug-cli 0.21.0-SNAPSHOT"
executor:
  name: "UpdateRugVersion"
  group: "atomisthqa"
  artifact: "atomist-rugs"
  version: "0.2.5"
  origin:
    repo: "n/a"
    branch: "n/a"
    sha: "n/a"

