dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
  - secure: QFU8y3I3wyEW3SF+7qgq6vFp2uWUGrvLayugmGd2mpBYQF2Fn9aYVR0z5pNm40jIyq8SYBYrm5O+nwhb3mTWa8/iryZaJkAKNBVQInVLtz5eiYS6++yJNa4R8ctq+ulviyNL2GEpZEw0f94UydRfCoVEN2hgZud5kgVzqfzZU2GAdYa+BpDfne9DH4Ezk9NONVt0SXAKp4jE6AnRinUcoe0ieM/6UjkPP7Cbpl20G/WbqjKNadXUV0JTcChKbz/aAJmQQDOVAc5wxqB8L2gS5qkfeOAXI5DnUVZaQqCQXl2h6Qr6G41ji23h6JZfgu/ReqAt58bA3aEp/eeTVxZBSfw4RUWsmRTOVD7aJFpWPVQ1vLbxqgKkWUzEiInzwswy8MSzdPNR+YQJwLQFJx5IZNVyrZ5XPioIwZrh9AGB5pKnQZKkX+QXGw1xe+l3XIikx0S9gBsfMBpUzaslu44gVYVEVYTBRSzNGGonLEDpN8LfykXMaoW4uE0Icz+FX7eOf0aAMOyKnY0Boy/TZI7syeHhWg4bq/DWQBSZ3T9IKJBRFkEM7aLaNAI73TOMjR10QATh654lJOQUSglCK7v4V7aUFR41PfB1H5JTGqITjWFAKN4pZEzTuKvVs7d+RjoEZrbGyAShEmqxclO5+4L0IO7yctWOHEGP3f1YD76I0Lk=
  - secure: gYdGPDzjve9r5mssPVXJU0eegYUazm3T+SBH0HW+/3h4RNZOF3GQF9Pz+/nkWZsxN9+9RV7xCq0U4qOFY/0kLC6k4x9+MyV2f3uk0qcWwUwYkIO37rMWvVC0VAwYIE510woiaU8VF+f/iOibFIV7iU1IwWyala/sYc9fVVbZDOmnmT/vos3H5DVe4LmcI0/5PvZyB2h7Q+tPUh5VBstkjUr1qKUScWB+Z75LLRMpMf7vFZA51kO1ooRoN+OVygk+80lL/HTy11ITeHcU67bPu1QvXQ0QDStUAlx8SEinjuhTeVcDbrkwaxqpiB3g2uY27Pk8f7sjppGbZPNvmNXRGJeCuVL85E6pNPJ7Km6QCLvGgRIIfOtkoIEss9uoQ9ZrYdJS31JuJV/K1yrXItOm/BYt7U3f9x04+649Nys76u1ylGluYyO0KDUnvJ4Ju3MYkE6UYV5daqdhII71JftnO+4zRqfW/gOHMPdrchVfcvgdy3cJL1W2djFOhlt2ox0GNJe+G+sxLqksPsfqY+cDIau72wRNN2pqERIqdovTcbYiPbIQjlxW67tj3X5fX1mUJWyL5+MuCxjH1TGCyEUK+It7d+UvhdjQckH6YLXbC4K9lCIeQd0qfKHEnOpfRQFRO4pWsmVtSugDRIvud9nQp9kLBOzvIyk9K7abk7vXoQw=
  - secure: MzeLHRJgZPzCCDs9bSa48t8pV1lXymTKlL215GQXESl+h6NT7pKZ5iy36uM9TYMMxaQnN7XVbkfp25vIlIpzl1TO/7Hu267/nQKFOWtX8N8gYSGt8sCBTgWlu3ccUFP8/C2StAxeF+humLWbcrU3BddJSSbzQIwL+nqm+qXUEWiMfuXXfkeG1ZJrwCWLWk2oSl/1YO5Nq5yW08BbJcUneNDq+7RbzsyB7ehxGzZSgqjfB8H41KMmdiUAR/gRAcvBYsVEEymQq8/0Lb8CzSQ0TZi6HFu4FuABMvpEEpr59FEycz+yVS+Ni41ad5Kk+/EdBFgs6gCRgLZQp/uaBO/5DRsoJztCX5OD11FHQrG+qjEYFRms/yAxy0eSMB8Ov/PC+pP/d4R16/YYS2XzdLJ29e057TjcyYIS0kKELMggupxYRzlYap83rfaB4NHkXLup7ccaOpFr2XxG21xcmHaJzx9yvZCSQJ7ECYHrm7QL+sDgAyhcyCTJfDRX7aK/+atluPyWugraoPUGeppjRm7V6Upo3r3+DzNCJV0TyTz3eMqJtq/TbXDlNj1zK3i7+uB2qGekcNC2JgrFyrWyfiai6AAarUthxfKEgWw8qU4CB95Y1ElUzRJbYgH+naLTMp8dXUET/f+CUL939y+USaefPBTSvWJtUGp7SX+ajyC3XeM=
install:
- nvm install 6.9.2
script: bash .atomist/build/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
