dist: trusty
sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - MAVEN_BASE_URL=https://atomist.jfrog.io/atomist
  - secure: gcGH3KlnNy9SzrKEGacG2etcwavNsWYRh8DLCzgIZvoxozbkFJ+scUci/e8MisXJqcdloImCKc7ej9cYUze/8zo4U3KnA8+Oqi3dVfIpgNZwoezEkNLAV3uFT0U0+jOVyTDEsdaqIaozdskfscGx8sBIUlEwuM5W+42bT0+RObWBMSNtkuZgQKBUEN5/47hIkzt+ntsfTXPr3zLQxfLRFk9jP++7RPgmo8+WtpeSIBwUn4pnLQSXhe6JyK+vksAj9G82WtPeqk7gXL0qWiGJuGlB8LhYW6+fwaNSBzO7MdpEYLyFLGHvq0AZkXRqZWoszgEgI8JyLr1JPUQYYqf+zTT2QPoT/dvsOCi2CZS01SLwhZbMvlnhW9q+8pGqP3s7xnsQUAB+pF/iUAdXzI9t46101qeE/Pn7nh4Lw0HcFpiT5un/jnPh6GkTwfbyZQVjV+ONAMBm2LsDRKw5+UGldigo37EY4uzfsqrhdeaDSbbCPrxJhNpg4x5NX1xtH9NPcSh7ae2IGMOX7Lj7gz5PR+pLdb7DgnEQCNNnRDHmjgs9Z3cDQOi9a1aGskK3+Gj7hBHEUEUR9TaFTP1gbS1Eum4W4jxYgS9N+GCsFaxlEzacBIpvyT+CnmRLcXCznUy+Xo7st9diXU7UYTURfrQt88CvhiPKU/6b8QeW36CYNNY=
  - secure: YI2UxVmmXNO06TgzNWR7eCJAn2MLmiGryTrkXN/B7AOefP4MO6bahdkTF7/pDLB8/UaChWFmoeChKkzTwSdQaRAdjP2tLsmgcZjo7OduElIWWTGv25RHIOBO5BbRQXCqTDKYyv1dTu9vK781440RAJxaoI/gDhUvIxKSP2rPwbqeMGLoLwXLPxw/W7+EU/oT6wvSLo3rin543eQ/KfcDf+ufXsVHCuTzF8Kk3eqp6AZEordFmQdtze9CXgEHHECukO7queRcXYuV8I8/sfZ1udhLAaepABX+zzycoLTv5l0UEQWzVSYZbnoEzaYdlr4M/py2ySDFREJaZhCQQbjRUW1BfnbgOQCFH0q3ku37IXn2SOWO1dSY2AkbFJ2VMO2JaqRLPM8QMr8Ua/ZsTAXRdf3FkYiHejwFtgxCBnOfABo3sMVLK+2xCXSqFgNogLerIRoFdy74lYS2yGKva3sLiZdc7jDIiIWS9kE0yD4VgXXJgUQvvV8Sfd7f1PZfEbYhLXYDXlDpDu7lxPMX3XJfAqSSo67OGuLsMFenLpQhyCpL2lNeXAZl5wJnCMROqHbV8d0X2dabVLiIRbGtSDBuhZWIdlhFv1u9i7XC1Jsud9nwet9AbpjiRRkMUWHAys3W66Pq2gdMMIUHntaO+lG+1DaxbUtxz2KcesKDJL62Hxc=
  - secure: jTQoPTZtyZSImL94suk/hRHx3lIrsaoDTFMRs2fjmwJD9GL180P6igMU7cGFB7QCcPDDwM/JbVVDN6qPlQKDpMnavfB3XF7bjrdL2MRrQfhpXQB5NMCz8c8DLTThmcx5pTPcpdUYhFf56L2hvDgEPw/EphEcWzYywf3h4FivCNFkc/K65f8trQ5O/9kA0ct2ezVAgZH51/SCqu1fFODv7LwQrTgn8h/K/AVdk0wKMlVW5u3TvN3TEnVd+G1xvFBeWPkpS78LnmbVr6RGTZ/YjOAaWtILMNO+NJAHAWPhGfdw9fbDA85S1s8UeIGR7OBhJJ6Fnu5uqboWq6W03Ca0rM346qkgw2dttWjJBGW88OskDbi2NdZ6LXajxXINdZCy+PI3DefjGo7BMbySCvAj6q23Uz3aWFB2HlOajrLSu1DN7NKvZvAZIyXufAH9c1flkhWnVVdnjSGs0HJeA1mqc7j6tr7UU+rVSXLA/kT/lOVuuUxWpums3gH66WGCqusJm9ewJRWr4Qhao+P6htxJMDPZzBPLPkGWTxkncHVVAoQ0fFSl5ETPyhv+FgssWa+p9ZwFoI0gMxTo39zuvnT450bz9s6is4cSIjruUOyIWa3jFDtbBt+i/NcelR30SBtdnfkkSBChc1Jb19DbL6jyuvttG/ZtFyiRxhI96xCsQRs=
install:
- nvm install 6.9.2
script: bash .atomist/build/travis-build.bash
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
