language: java
install: true
script: bash travis-build.bash
jdk:
- oraclejdk8
branches:
  except:
  - /\+travis\d+$/
env:
  global:
  - secure: lyoLR7+HWsSNmlHzxof0i6iGiDJDwRO21LJ57wXzqZiUnWhgnJ6eHSM7IX2rxyNMnGWIf8i9wiKqjFHLoAVb1n0qzPF4GgNMXz/l1O5GeSEw1sAM8rIdqO9SnYEFcNWQ2UJljl7yHZiEFHBYBKpZgKW25PfkuL7p6TL8z4ZFwOIXH5T6cp7TfrUwTVem/n8nIlnjzImuehX6e52QLySK88/m3qknREfkERMPtSsaOqwWSoc9RKmUOfV1JG3tfq8Op84wP5/mSVM3j4zyMCWPMyz6nzES7ua7LauGLn19TLN/9A/6QVAmEEQnG2BNLTFG5OUDGl1BoZaXyyEgTds1wACpRJQBMx7f7NtvkiMuMYqGEf02igKVlT78zSLpA0xXpjy14crQethGzVzfit8c13GXBDFa/zsYexuu6d0tCcd8xRRkqEKryrKVwqFybLJqLqRzf5tvlAdRZxpYOBFSSi06K54O6JtLHpcGnan+3qjZSSxRlAWSdWLUqjmO/dbm/axIU/mhR+Wl2Fvnu769JelYtNGPyk36Bir7+S3d+8Z16LDxRQ3U8vvEMs38UF9lSx+ApgsJBtGzHL/qEZk2PRxv1GvAvchAxizhbs4fiw5LFt3lroSaF52NWFgmgwmop3KVVbgfZt3Gfi0F3cb+VoW/WH0bFoDUED7z0Gn1aZI=
  - secure: h37oQ5dhMqX4P8XngQXtmOILGmQQCblIuJWhpBwukxciyNvQpM1R45jY2xvoNhDewyXq7ah+y0BIVseXB1/dodb2yRMVA6n4psazpOh4nt73kqYKu4/AE32iLkcq/jrPFjRWRzbcf7NJsM8pIfpwMpb6M6TxlvltUWX1dHIZ4zw3g0L/Ec8r7bbEOEoobVtS9Jx43uRHFW8t05npWmVWi53lyp9rangmNmUjq/uFGZMengKMb+iFzXDL0qw9StUYngtgHSNxjJxQ5A4d9Q7Nf7H08kmkiFQMs1e71kkA04BDrn55C/SfSQAcJs4J9udbh3+R1rOqH1IVL5uZ5aur6yDncNi2rmyFiZflk6Iawp9Ng5+8HM8lB9TiLzKB+IMOsRhJOSko3y1GuxnGjcxa99zCXzYPHwYoym1wbngXrtCOn9oyyf0yKaVhHxCmU9u3eyWikXUvlKZVyMdlq2ACKQ8DRsxuzuUKUQCE4GFSfaGqII7XtWvjqeszRQ3yb5wEHQB+LwQVy8TiVMGvyijFOgCUKi5buzINeRKn+DA8+4XUCYmPf56zYqyObH23VVURYMimj75r3g90fX+8LtV7j0gTPstyG5Kuvc0XyTF7088zzQ8IejczshYGVAl0ro7akyWLdsNyZFE06vQipOg+gPHtkgbVxmqQN8ZJzNSjigg=
  - secure: MjGgXCFkQHzHwm91T0XMgpHPPY5h4RJjTeUXAUADeDJOBrPiuD1gRmT/aZ5b5iuCLS+Xl/YKKeCBRN0zUbdFX7nnyHUh/3hdjTVN7AdoBvddpSrsLxigVCfDGuxTYdGs+yzADrYMqW7MedWgxdr75C0cQgvOgOmgx44uYBku8RFCtBcE4ZlU7OC48B01Nom9Mhvh0s2kcyaA3HKjyOE57l31yTriTy14XhBkGfd56b97GVc/wKlkKGivm0ATR3VYBCYCqSJOuMih2eOA0ZbXB4LfApoQ+vafEX04EVjA6C/GV+3HU9q/zp4FOoumfPaFpIl/WzM7hWBVza2vroM0ON/QnTMscz//0bWc/Y4U/c7CZ5FMZDat+HdZjUGNqEp4M23wSOWYKg6unLjSsy4nok8DTPCVaqoQlq/KGYaJe+041ECbnBmeaz6chJfp221CMy4pRLTwyfwIPchsFfyU/MGkVcksf9wZC9+7PQKLaMC6opFUMB7go1AfHWoHWnFavHBOLk41JuTyrEwvvDAMzhOytz5xPf60Qg1QUANpE9R3ayRDnyvYJNqjmk719s+DQ95ob2wR2M8qp4I4qPcYjGZBnRbg0oDZUlg7oK14Kif+whmMSYP9U22FkGxNqasui2Gyhx7MsHi/SvhT2fG0z4hkMCvtWIaW2GAN3lIFPds=
notifications:
  email: false
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
cache:
  directories:
  - $HOME/.atomist
